### ISSUE TITLE
Fix CHANGELOG ios 

### ISSUE THREAD

**Issue by Gianfranco97** [flyve-mdm/flyve-mdm-press-kit#29]
Hi, @hectorerb 

currently the changelog look like this:
``` yml
---\nlayout: modal\ntitle: changelog\n---\n
```

that's wrong, the correct way they should look is like this:
``` yml
---
layout: modal
title: changelog
---
```
Thanks.
