### ISSUE TITLE
Blacklist of circleCi

### ISSUE THREAD

**Issue by Gianfranco97** [flyve-mdm/flyve-mdm-press-kit#36]
Hi, @hectorerb and @rafaelje 

it is necessary to add the 'gh-pages' branch to the blacklist of circleCi to prevent it from continuing to run every time a push is made

Thanks.

**Comment by Gianfranco97** [comment]
Example: 
``` yaml
general:
  branches:
    ignore:
      - gh-pages
```
